travis:
  secure:
    BINSTAR_TOKEN: bXXjLFsqgTD3s69MRHpYZUBG81FGEwi8569OKyDBVL8lAp0uBxgKNyqI1jtbvky82XIUSEgLFIXHN7F+VR9YhVJxqskHZInDEII03aeGx5FOrarpUYKo/HhLki4n3L3guvmSgWEGVC4mcZpS1MxWXK6lhZmeEOINkL29I5uoBW/fMueYcmntMEoNESr04JFrEHNVacDsyme0QHtHSA6PuTC8wgeu/s1aGVydg7zaKuTWE3hz6r7R3F/ERxSIDf6zNBuHOxc5HbUnd9HtmBhOwCvdkzUrTMVoy7EG0vUj/7PaIBRJrpJId5FQyIWMPEqGW/Z/QGLSXZthE/F23SWA7RW8QqVebFyymVCNCGW6Mh2l0sT7Ke8E8N1IfpyaolE9Iqc/idX5PDdZGhovqUDecBJqiYzFFejsGQx7P28+5AOiqdlnps0++HrrLnkpF8ZCu5gbREDSrtwIosCP36MgmjurcFQUcNL5FvvA7vXKsRBu/ejdPlUWfCgjAuWQUOcBEZKmygMfC/dRnNIMlbNRVys0mW40IKpvJybmmEl76qud4GPvl0sXIDJ2ADz0FGgX0F/LI5yYEHC1J9hXBC25vEm3LG0zOLkuJiPoJjwW6OgpLckIy3NQf5qH1eR/Oq4O0pAQ3juI+j9B0y2MKfzXB+J4HHO/IyY5+oQvnjytXxc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
