travis:
  secure:
    BINSTAR_TOKEN: XT6UkLcBbuRzWRZhf1suRHeLyOm0sXRwoB22OVALiluJSf+0NtbkkFE0nchM/k46m0D9iJQ2IC1PODPAUlIfYGHy6ZDY2OUui3dksYnsnCl05fmL2upllfVq93mYmBNx86e0l2HRFwDH5Sosr51X7MUbpkOqrbXWWP5OfJi6WsRX2aH0fxd/bXlX1my3SCaPfpAnIredDgFBPfjvAlzExxUIOlwFoJYcHBasA3XOzS/YDR8aiavVIRMr0oMFaQup2FOeChGiXb0IXWXe9PjiV9yScM136Zh2hsntdnGoTWYBhYtqq+fU230TdVAcCiqxRi/c6vJTjtcTCHrC6FYytOb48qglhW1SmWvbTV3r2gGrrIffPy1oNgJy0F4HE3bZttrBgFb5kJnrXoQIFVF9mRrK8mtv+kRwnk5NmIG1RkECw3Ro8HTXxHltpd23V9u9McHq8mUeiCFwH/E8rki339JTv6F+f9z+sFRKqPGTQ7VfDwNt4Rdp95nPrZmNktwGyKL/7tjwfZKmICaZca1wt7FsVUWOL8rFTvFwPwIz0gQ24Pk/SApp1U5OawxJIwB7olO3MQyuWFPrV0RGNfdmzDDNqQmh0zbEeIFO72kaNcpIuIe+uwqpIR80QKuHqCbcE7AlQipomFI7zkl67Le37x9CtVbGuwyiPwgjUC3NIlQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
