travis:
  secure:
    BINSTAR_TOKEN: R7p6IFcehGaKfHqm+uGU9nrsI9wVHZyOTU+LaXMRJgoEZgIC/YITt1r37Bpj1ojt6Zd6rxbcUtXLCb0QIgUTIQ3RieedOYkr5W4II6cuhFhiB50Qm6RwoT5Lh6SPlOyvyXcA+V60p3+jcZk8g/I57lj1gIKbulkf+KNjoWWx+NKQXLtY6Zzfz7bNggfl2U8eVIxrahnlJXXWO57lp+6CWPvDuVBQivIuirafEjUhKHjyDEyIg2PyLGO0C5y6SA0cIWXSxwmo0AdDmhU3C1jqAlK1SNSM4pxGviJUY+dNHPU+om63emmrghpqzCmGdPLQYEVFjwVErLGmFNxToNq+S2U9nWQSKqur23+k8Wid22OP7IymbBWlwHMs8/R6L1S8/ZiCHviWfh6gr7hBTBRJyLhw3HBKYKcD89wSsHyGdsdI6aHktFn+dQ7H/HD11akJD5wJNHebh5QcBog+U/6QxWmc76Dyi+BqZT93AKzYXTKeruTnkJP42WvGhFucXFyzB984rg+AZb5ZDOjUQfob/qL/KLbEhySajfTThQu02XpCiLKHpQK+8wT6eJCoHsm7gmiXRBGvu+BK4ssCBtt2qdjicxwsBqd3iNQ5MnTPDssp9ZHlvvYt8JWhS6soVk7bRSUru65lzqcY/xvweoKjGTko27rlsUgVKUpgAiV1kl0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
