travis:
  secure:
    BINSTAR_TOKEN: AFIq379+fDVA+GQaGnexxwDLgz8cMnqPb1KVdKhKGF9AfKfbm9z1eTSoKXz9mpK3JUZ7OwxF25oFyeSR0nJBFtfp45ltK+DPHR32XnzRHRYSVr+hcyAUeSTDK0tWpVzWo0JSEVK7oG7JEA2JjXhxyBXmlHf/IQPQVpbB0bschUobpm3f/sBvJ4+hrXxVs7n8vdezHYB4yQ1eXbEow6r1ysOGeFCmZv4nODeSAa19SBTg1tQANsTy2AH4P8q87siuWx+njQYYZpc+CJIIkudnbO6COv+8WD5H+yheDnYup/2tyPioiC7VJohrPyB22psQhwKX2UL8FIH72omK4Gdb5zaWGvlQ7O28D8wckCaOTvipsQiK4q2qjpm2u3MSVSVR3KvXK0ks07Pmq2ofnTReg8t/mCjsKSDLXcQ0d3a0FBY2B+dT8CEcOFrAsPSC0KsCMb5sXfy+H/41YJHBLuJeHXn+y+N7aiYPLcxuVw3/oayLTiEyjJjbDq2qUhYPW3k7mX184L4cRPbpvrbGRolVvd6KXbn9giFKTdS2Yqz6GGunm3hiEqeK0QjGl230lVZNr39qP3HZDB24YEBBXoT4DJjdJbaMOIWfJlCpL71vvBiYuUqbHNyTKDUXyEFeqSZv6/DFSICHgMiyuG+csiRctHgw1ieLIhLY2JQVE1Gaq+Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
